language: go
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
go:
  - 1.2
  - 1.3
  - 1.3.1
  - tip
script: make test
notifications:
  webhooks:
    - https://docker-build-server.modcloth.com/docker-build/travis
  on_success: always
  on_failure: never
