language: go
matrix:
  fast_finish: true
go:
  - 1.2.2
  - 1.3.3
  - tip
script: make test
notifications:
  webhooks:
    - https://docker-build-server.modcloth.com/docker-build/travis
  on_success: always
  on_failure: never
