language: go
matrix:
  fast_finish: true
go:
  - 1.2
  - 1.3
  - 1.3.1
  - tip
script:
- cd /home/travis/goopathsrc/github.com/rafecolton/docker-builder && git fetch
- make test
notifications:
  webhooks:
    - https://docker-build-server.modcloth.com/docker-build/travis
  on_success: always
  on_failure: never
