language: go
sudo: false
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
go:
- 1.2.2
- 1.3.3
- tip
install:
- make build
script:
- make test
after_success:
- make goveralls
env:
  global:
    secure: N9ov/trnA42r0ZMo7iHWeMY65vWQEA3z17A9RCXsblqxOdKjGJAdEqKHKmNWlG4yFP/3B5Pyc39xZcIC1p3RucWsvuRuDaFMV0d4agmqkWUIyQl+SVKQGYeQedvjgcMQcGRlqTYgVNGn0ugyX4VU/BdkKH0G+DeEfQ/19k+YXP8=
